// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answer-versions/{id}": {
            "get": {
                "description": "Returns all versions of a specific answer by answer ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "answer-versions"
                ],
                "summary": "Get answer versions by answer ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AnswerVersion"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid answer ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/answers": {
            "get": {
                "description": "Returns list of all answers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Get all answers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Answer"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new answer with text, tutor_id, question_id. Create a new answer_version with answer_id, answer_text, tutor_id, answer_number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Create new answer and records the version",
                "parameters": [
                    {
                        "description": "Answer data",
                        "name": "answer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnswersSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Answer created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/answers/{id}": {
            "get": {
                "description": "Returns answer by specified ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Get answer by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Answer"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Answer not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update answer with text, tutor_id, question_id and edit flag. Create a new answer_version with answer_id, answer_text, tutor_id, answer_number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Update answer and records the version",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Answer data",
                        "name": "answer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnswersSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Answer updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Answer not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/answers/{id}/deleteBy/{tutor_id}": {
            "delete": {
                "description": "Delete answer by ID and mark all answer versions as deleted with tutor who performed deletion",
                "tags": [
                    "answers"
                ],
                "summary": "Delete answer by ID with version tracking",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tutor ID who deleted the answer",
                        "name": "tutor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Answer not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/question-tags": {
            "get": {
                "description": "Returns list of all relations between questions and tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question-tags"
                ],
                "summary": "Get all question-tag relations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QuestionTag"
                            }
                        }
                    }
                }
            }
        },
        "/question-tags/by-tag/{tag_id}": {
            "get": {
                "description": "Returns list of all relations between questions and tags by tag ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question-tags"
                ],
                "summary": "Get all question-tag relations by tag ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QuestionTag"
                            }
                        }
                    }
                }
            }
        },
        "/question-tags/{question_id}/{tag_id}": {
            "post": {
                "description": "Associate a tag with a question using IDs from URL path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question-tags"
                ],
                "summary": "Add tag to question",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete relation between question and tag by their IDs",
                "tags": [
                    "question-tags"
                ],
                "summary": "Delete question-tag relation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid question ID or tag ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Relation not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/question-versions/{id}": {
            "get": {
                "description": "Returns all versions of a specific question by question ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question-versions"
                ],
                "summary": "Get question versions by question ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QuestionVersion"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid question ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/questions": {
            "get": {
                "description": "Returns list of all questions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Get all questions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Question"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new question with text, tutor_id. Create a new question_version with question_id, question_text, tutor_id, version_number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Сreates a new question and records the version",
                "parameters": [
                    {
                        "description": "Question data",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QuestionsSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Question created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/questions/{id}": {
            "get": {
                "description": "Returns question by specified ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Get question by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Question"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Question not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update question with text, tutor_id and edit flag.Create a new question_version with question_id, question_text, tutor_id, version_number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Update question and records the version",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QuestionsSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Question updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Question not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/questions/{id}/deleteBy/{tutor_id}": {
            "delete": {
                "description": "Delete question by ID and mark versions as deleted",
                "tags": [
                    "questions"
                ],
                "summary": "Delete question",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tutor ID who deleted the question",
                        "name": "tutor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Question not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/simple-search/{name}": {
            "get": {
                "description": "Search questions by exact tag name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search 🔍"
                ],
                "summary": "Search questions by tag name (exact match)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag name to search for (exact match)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Tag name parameter is required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Returns list of all tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get all tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tag"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new tag with tag name and optional tutor_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create new tag",
                "parameters": [
                    {
                        "description": "Tag data",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TagSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tag created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags/name/{name}": {
            "get": {
                "description": "Returns tag by tags name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get tag by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tag"
                        }
                    },
                    "400": {
                        "description": "Invalid name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Tag not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "get": {
                "description": "Returns tag by specified ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get tag by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tag"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Tag not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete tag by ID (cascades from questions_tags)",
                "tags": [
                    "tags"
                ],
                "summary": "Delete tag by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Tag not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tutors": {
            "get": {
                "description": "Returns list of all tutors",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutors"
                ],
                "summary": "Get all tutors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tutor"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new tutor with full name and email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutors"
                ],
                "summary": "Create new tutor",
                "parameters": [
                    {
                        "description": "Tutor data",
                        "name": "tutor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TutorSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tutor created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tutors/{id}": {
            "get": {
                "description": "Returns tutor by specified ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutors"
                ],
                "summary": "Get tutor by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tutor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tutor"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Tutor not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update tutor with full name and email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutors"
                ],
                "summary": "Update tutor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tutor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tutor data",
                        "name": "tutor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TutorSwaggerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tutor updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete tutor by ID",
                "tags": [
                    "tutors"
                ],
                "summary": "Delete tutor by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tutor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Tutor not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Answer": {
            "type": "object",
            "properties": {
                "answer_text": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_edit": {
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.AnswerVersion": {
            "type": "object",
            "properties": {
                "answer_id": {
                    "type": "integer"
                },
                "answer_text": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delete_by_tutor": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_delete": {
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                },
                "tutor_id": {
                    "type": "integer"
                },
                "version_number": {
                    "type": "integer"
                }
            }
        },
        "models.AnswersSwaggerRequestBody": {
            "type": "object",
            "properties": {
                "answer_text": {
                    "type": "string"
                },
                "question_id": {
                    "type": "integer"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.Question": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_edit": {
                    "type": "boolean"
                },
                "question_text": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.QuestionTag": {
            "type": "object",
            "properties": {
                "question_id": {
                    "type": "integer"
                },
                "tag_id": {
                    "type": "integer"
                }
            }
        },
        "models.QuestionVersion": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delete_by_tutor": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_delete": {
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                },
                "question_text": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "integer"
                },
                "version_number": {
                    "type": "integer"
                }
            }
        },
        "models.QuestionsSwaggerRequestBody": {
            "type": "object",
            "properties": {
                "question_text": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.TagSwaggerRequestBody": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "integer"
                }
            }
        },
        "models.Tutor": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.TutorSwaggerRequestBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2709",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Knowledge Base API 📚",
	Description:      "API для базы знаний с вопросами и ответами",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
